name: Manual Tests

on:
  workflow_dispatch:  # This event allows manual triggering
  push:
    branches:
      - testing

jobs:
  test:
    runs-on: ubuntu-latest

    container:
      image: ubuntu:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install dependencies
      run:  |
        set -e
        apt update
        apt install curl qemu-system-arm python3-pytest make gcc gcc-arm-none-eabi -y
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        export PATH=$PATH:$HOME/.cargo/bin/
        rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
        rustup target add thumbv7m-none-eabi
        cargo install rustfilt

    - name: Run tests
      working-directory: tests
      run: pytest-3 test.py
