name: Nightly Tests

on:
  schedule:
    - cron: '0 0 * * *'  # This cron schedule runs every night at midnight UTC

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run:  |
        set -e
        apt update
        apt install curl -y
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- --default-toolchain none -y
        /root/.cargo/bin/rustup toolchain install nightly --allow-downgrade --profile minimal --component clippy
        apt install qemu-system-arm -y
        apt install python3-pytest -y

    - name: Run tests
      working-directory: tests
      run: pytest tests.py
